import type { Metadata } from "next"
import { Recursive } from "next/font/google"
import "./globals.css"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import { Toaster } from "@/components/ui/toaster"
import Providers from "@/components/Providers"
import { AppSidebar } from "@/components/app-sidebar"
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar"


const recursive = Recursive({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">

      <body className={recursive.className}>
        <div >
          <SidebarProvider>
            <AppSidebar variant="inset" />
            <SidebarInset>
              <main>
                <Navbar/>
                <div className="flex-1 flex flex-col h-full">
                  <Providers>{children}</Providers>
                </div>
                <Footer />
                <Toaster/>
              </main>
            </SidebarInset>
          </SidebarProvider>
        </div>
      </body>
    </html>
  )
}