import type { Metadata } from "next"
import { Recursive } from "next/font/google"
import "./globals.css"
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar"
import Navbar from "@/components/Navbar"
import Footer from "@/components/Footer"
import AppSidebar from "@/components/app-sidebar"
import { Toaster } from "@/components/ui/toaster"



const recursive = Recursive({
  subsets: ["latin"],
  display: 'swap',
})



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={recursive.className}>
        <div className="flex flex-col min-h-screen">
          <SidebarProvider>
            <AppSidebar variant="inset" />
            <SidebarInset>
              <Navbar />
              <main>

                {children}

              </main>
              <Toaster />
              <Footer />
            </SidebarInset>
          </SidebarProvider>
        </div>
      </body>
    </html>
  )
}